[
tool.black
]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[
tool.isort
]
profile = "black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[
tool.bandit
]
exclude_dirs = ["tests", "venv", ".env", ".venv"]
skips = ["B101"]  # List of test IDs to skip
